### ISSUE TITLE
STREET BEAT #61

### ISSUE THREAD

**Issue by garethhorner** [ttillberg/acf-vimeo-pro-data#14]
Hi Theo
I've installed the plugin, input access code and can query videos from the field when adding a new post - however when the desired video is selected the following message is displayed… 

> The video 'STREET BEAT #61. Фрагмент - R-FSK Party.' was found but doesn't provide any files.
> Make sure the video the video provide external access to its files.

The access token has public, private and video files selected as required, any idea? 
Best
Gareth

**Comment by ttillberg** [comment]
Hello Gareth !

I've seen this before, just from the top of my mind:
- Make sure you have a PRO account
- Check "Video Files" is included in the scopes of the App as well (this is relatively new I think)
- On Vimeo, choose the file a check if there's no setting that would restrict the access to the video files. i.e. Video > Distribution > Files should be accessible

![image](https://user-images.githubusercontent.com/557990/50831523-63d6b080-134b-11e9-8750-37b122270d39.png)


Let me know how it goes

Cheers,
T

**Comment by garethhorner** [comment]
Hey Theo
Thanks for the quick response — so I deleted the field, regenerated a new key, input in the settings created a new field and now I can select the first video but the rest still result in the STREET BEAT error…

![vimeo1](https://user-images.githubusercontent.com/10637759/50834606-608ff480-134c-11e9-9572-604322b975f0.jpg)
![vimeo2](https://user-images.githubusercontent.com/10637759/50834607-6259b800-134c-11e9-9d56-36df05f1a3a7.jpg)

I've compared settings side by side and all videos are the same

**Comment by ttillberg** [comment]
Can you fetch other videos or is it all the same ?

I remember someone having similar issues while trying to fetch a video of which he wasn't the owner, i.e. somehow shared on his feed from an other source. Other than that I can't think of anything ATM.

**Comment by garethhorner** [comment]
Yeah it's really bizarre - only other thing I can think of is the account was only recently switch to Pro from Plus. I'll keep playing… Thanks for your help man!

**Comment by ttillberg** [comment]
That shouldn't be a problem. However if you're not the owner of the video it won't work.

Can you see the files like this : 

![image](https://user-images.githubusercontent.com/557990/50837237-722cc880-135b-11e9-950f-e5175e0236bb.png)

**Comment by garethhorner** [comment]
Yep - have access to the account 
<img width="608" alt="screenshot 2019-01-08 at 15 15 30" src="https://user-images.githubusercontent.com/10637759/50839492-596ee380-1358-11e9-82ff-f08baa016f6f.png">

**Comment by ttillberg** [comment]
Any luck with this ?

What could help me diagnose would be looking up the network tab just after having selected a video from the drop down and to share the XHR/JSON response.

The endpoint I'm looking for looks similar to this: `https://api.vimeo.com/videos/02345678923?fields=name,description,link,...`

If you find out, I'd love to know in order to amend `README` so nobody else gets stuck in the future.

**Comment by garethhorner** [comment]
Hi Theo
Still the same issue unfortunately — I've just cleared and reselected a video in the field, this appeared in the network tab under **307542764** 

`{
    "uri": "/videos/307542764",
    "name": "2000 Year Collaboration (The Prophet), 2018 - VIDEO DOCUMENTATION OF INSTALLATION",
    "description": "An animatronic mouse partially visible emerging from a hole broken through the gallery wall. The mouse delivers a 9 minute monologue using the voice of the artist's 9 year old daughter, imparting a philosophical speech based on the final scene of The Great Dictator  (1940) by Sir Charles Spencer Chaplin, rewritten from a post-simulacrum perspective.",
    "link": "https://vimeo.com/307542764",
    "duration": 527,
    "width": 1920,
    "height": 1080,
    "created_time": "2018-12-20T18:25:09+00:00",
    "modified_time": "2018-12-20T18:35:14+00:00",
    "pictures": {
        "sizes": [
            {
                "width": 100,
                "height": 75,
                "link": "https://i.vimeocdn.com/video/747521829_100x75.jpg?r=pad"
            },
            {
                "width": 200,
                "height": 150,
                "link": "https://i.vimeocdn.com/video/747521829_200x150.jpg?r=pad"
            },
            {
                "width": 295,
                "height": 166,
                "link": "https://i.vimeocdn.com/video/747521829_295x166.jpg?r=pad"
            },
            {
                "width": 640,
                "height": 360,
                "link": "https://i.vimeocdn.com/video/747521829_640x360.jpg?r=pad"
            },
            {
                "width": 960,
                "height": 540,
                "link": "https://i.vimeocdn.com/video/747521829_960x540.jpg?r=pad"
            },
            {
                "width": 1280,
                "height": 720,
                "link": "https://i.vimeocdn.com/video/747521829_1280x720.jpg?r=pad"
            },
            {
                "width": 1920,
                "height": 1080,
                "link": "https://i.vimeocdn.com/video/747521829_1920x1080.jpg?r=pad"
            },
            {
                "width": 1280,
                "height": 720,
                "link": "https://i.vimeocdn.com/video/747521829_1280x720.jpg?r=pad"
            }
        ]
    },
    "files": [
        {
            "quality": "hd",
            "type": "video/mp4",
            "width": 1920,
            "height": 1080,
            "link": "https://player.vimeo.com/external/307542764.hd.mp4?s=69a2612a6d2404ed27a6b7fc1cba348472ad42d9&profile_id=175&oauth2_token_id=1160977170",
            "created_time": "2018-12-20T18:30:12+00:00",
            "fps": 30,
            "size": 355097273,
            "md5": "5237f04181155b1989031f3bd48a3c31"
        },
        {
            "quality": "sd",
            "type": "video/mp4",
            "width": 960,
            "height": 540,
            "link": "https://player.vimeo.com/external/307542764.sd.mp4?s=6528f4849cc7f3e865d6489d8db82c9dfbe96da2&profile_id=165&oauth2_token_id=1160977170",
            "created_time": "2018-12-20T18:30:11+00:00",
            "fps": 30,
            "size": 89680393,
            "md5": "152d17d9fbdc423aaf6a4eba3233fc36"
        },
        {
            "quality": "hd",
            "type": "video/mp4",
            "width": 1280,
            "height": 720,
            "link": "https://player.vimeo.com/external/307542764.hd.mp4?s=69a2612a6d2404ed27a6b7fc1cba348472ad42d9&profile_id=174&oauth2_token_id=1160977170",
            "created_time": "2018-12-20T18:30:11+00:00",
            "fps": 30,
            "size": 164081068,
            "md5": "fd9f120d681de5d1474145e23fa0c8a0"
        },
        {
            "quality": "sd",
            "type": "video/mp4",
            "width": 640,
            "height": 360,
            "link": "https://player.vimeo.com/external/307542764.sd.mp4?s=6528f4849cc7f3e865d6489d8db82c9dfbe96da2&profile_id=164&oauth2_token_id=1160977170",
            "created_time": "2018-12-20T18:30:11+00:00",
            "fps": 30,
            "size": 35865203,
            "md5": "12090f5678ecc3fa3acdd0f87b31af1f"
        },
        {
            "quality": "hls",
            "type": "video/mp4",
            "link": "https://player.vimeo.com/external/307542764.m3u8?s=a267f07b436d280f3d41466e49ff210002159c66&oauth2_token_id=1160977170",
            "created_time": "2018-12-20T18:30:12+00:00",
            "fps": 30,
            "size": 355097273,
            "md5": "5237f04181155b1989031f3bd48a3c31"
        }
    ]
}`

**Comment by garethhorner** [comment]
A screenshot if it's easier to decipher 
<img width="651" alt="screenshot 2019-01-10 at 11 11 54" src="https://user-images.githubusercontent.com/10637759/50964992-a245aa00-14c8-11e9-80ae-5a5f1e1e531f.png">

**Comment by ttillberg** [comment]
Thanks for that ! It looks correct.

Just a guess but could possibly be that the response is not interpreted as JSON for some reason (could be some some proxying, browser plugin, who knows). Have you tried with a different browser ?

Having a look at it now. BRB

**Comment by ttillberg** [comment]
😓 No luck really. Just can't replicate anything.

I've updated the plugin "1.1.2" with some extra logging. 

*If you have a chance*, could you please update, refresh, try over again and feed back (copy paste or screenshot):

1. The error message
2. Any message / error inside the inspector console

Thanks

**Comment by garethhorner** [comment]
Hey Theo
Thank you man! Massively appreciate all of this. These are the messages under the inspector… 

<img width="851" alt="screenshot 2019-01-10 at 17 57 56" src="https://user-images.githubusercontent.com/10637759/50987358-5a8f4480-1501-11e9-9ed7-fcaeef92ac87.png">

Still getting the same issue

**Comment by ttillberg** [comment]
My observations from the output:

- The first video (`2000 year collab...`) seems to be all good so I can't understand how it fails for now.
- The second video (`STREET BEAT`) doesn't provide any files indeed. This is an anomaly from Vimeo unless the video has been uploaded from another account. Is "Yuliya Biziuk" your account (where the app sits) ?

**Comment by garethhorner** [comment]
No the second video just seems to constantly invade - when you focus the search field and the list appears, the first video is always **2000 year…** and that works. Clicking any other video in the list brings up **STREET BEAT** ha

Would be helpful if I sent you a login?

**Comment by ttillberg** [comment]
🤦‍♂️ Ahhh I see ! So I guess it's more of an UI bug. Yes login would definitely work do you want to DM on twitter ? Also what's your browser ?

**Comment by ttillberg** [comment]
5702595 closes the STREET BEAT bug
